### ISSUE TITLE
Systemless AdBlock v2.01 NOT SOURCE

### ISSUE THREAD

**Issue by Insidevk18** [Vaz15k/Systemless-AdBlocker#1]
After downloading the latest version (v2.01), when flashing in KernelSU, it appears as v2.00, the module asks for an update, however it does not find the source.

Attached screenshots
![Screenshot_2024-05-22-01-32-47-654_me weishu kernelsu](https://github.com/Vaz15k/Systemless-AdBlocker/assets/94028610/b8d95097-fc89-4957-83ce-a6d4142501a9)

![Screenshot_2024-05-22-01-32-51-906_me weishu kernelsu](https://github.com/Vaz15k/Systemless-AdBlocker/assets/94028610/8fb8e8cb-9b0c-4713-94ab-d30d11108271)

![Screenshot_2024-05-22-01-33-19-278_me weishu kernelsu](https://github.com/Vaz15k/Systemless-AdBlocker/assets/94028610/49e45476-6b9f-4d59-9655-a49ad73e3958)

**Comment by Vaz15k** [comment]
I had forgotten to fix the zip link.
Thank you for the warning!!

**Comment by Insidevk18** [comment]
> I had forgotten to fix the zip link. Thank you for the warning!!

Thanks to you for your work.
One question, this module doesn't have to configure anything in Termux, right?
I ask this because I used to use "Malwack module" before and with this I had to go to Termux to configure it.

**Comment by Vaz15k** [comment]
> > I had forgotten to fix the zip link. Thank you for the warning!!
> 
> Thanks to you for your work. One question, this module doesn't have to configure anything in Termux, right? I asked this because I used to use "Malwack module" before and with this I had to go to Termux to configure it.

 No, you don't need any configuration, just install and use...

**Comment by Insidevk18** [comment]
> > > I had forgotten to fix the zip link. Thank you for the warning!!
> > 
> > 
> > Thanks to you for your work. One question, this module doesn't have to configure anything in Termux, right? I asked this because I used to use "Malwack module" before and with this I had to go to Termux to configure it.
> 
> No, you don't need any configuration, just install and use...

Ok, thanks for the clarification. :)
