### ISSUE TITLE
English source variant 

### ISSUE THREAD

**Issue by stablestud** [Vaz15k/Systemless-AdBlocker#2]
I'm trying to extend your module with additional hosts (porn, gambling, unsafe sites) which should work as a variant to the existing version.

But I'm having difficulties working with the repo as most comments and some strings are not in English.

Could you update those to be in English, then everyone in the world can contribute.

Thanks ;)

**Comment by Vaz15k** [comment]
Thanks for your interest!
I made the changes for English!
