### ISSUE TITLE
Block tigr1234566.github.io

### ISSUE THREAD

**Issue by DerGoogler** [Vaz15k/Systemless-AdBlocker#3]
TikTok Mod Cloud update dialog

**Comment by Vaz15k** [comment]
Sorry for the delay, I was traveling...
I've already updated, the block will be valid on Monday!!
Thanks for the contribution!!

**Comment by DerGoogler** [comment]
np

**Comment by ZG089** [comment]
UPDATE: The site is 404 now, I've just checked it.

**Comment by DerGoogler** [comment]
@ZG089 those domains from the tiktokcloud mod
